//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace hotel_bookings.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class admin_role
    {
        public int admin_id { get; set; }
        public int role_id { get; set; }
        public string note { get; set; }
    
        public virtual admin admin { get; set; }
        public virtual role role { get; set; }
    }
}
