//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace hotel_bookings.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class booking_details
    {
        public int id { get; set; }
        public int room_id { get; set; }
        public int booking_order_id { get; set; }
        public Nullable<int> price { get; set; }
        public Nullable<System.DateTime> check_in { get; set; }
        public Nullable<System.DateTime> check_out { get; set; }
        public Nullable<int> room_number { get; set; }
    
        public virtual booking_order booking_order { get; set; }
        public virtual room room { get; set; }
    }
}
