//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace hotel_bookings.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class contact_details
    {
        public int id { get; set; }
        public string address { get; set; }
        public string phonenum1 { get; set; }
        public string phonenum2 { get; set; }
        public string email { get; set; }
        public string facebook { get; set; }
        public string insta { get; set; }
    }
}
