//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace hotel_bookings.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class feature
    {
        public feature()
        {
            this.room_feature = new HashSet<room_feature>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string icon { get; set; }
    
        public virtual ICollection<room_feature> room_feature { get; set; }
    }
}
