//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace hotel_bookings.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HotelBookingEntities : DbContext
    {
        public HotelBookingEntities()
            : base("name=HotelBookingEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<admin> admins { get; set; }
        public DbSet<admin_role> admin_role { get; set; }
        public DbSet<booking_details> booking_details { get; set; }
        public DbSet<booking_order> booking_order { get; set; }
        public DbSet<carousel> carousels { get; set; }
        public DbSet<contact_details> contact_details { get; set; }
        public DbSet<content> contents { get; set; }
        public DbSet<feature> features { get; set; }
        public DbSet<news> news { get; set; }
        public DbSet<order_service> order_service { get; set; }
        public DbSet<rating_view> rating_view { get; set; }
        public DbSet<role> roles { get; set; }
        public DbSet<room> rooms { get; set; }
        public DbSet<room_feature> room_feature { get; set; }
        public DbSet<room_images> room_images { get; set; }
        public DbSet<room_style> room_style { get; set; }
        public DbSet<service> services { get; set; }
        public DbSet<setting> settings { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
        public DbSet<user> users { get; set; }
        public DbSet<user_question> user_question { get; set; }
    }
}
