//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace hotel_bookings.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Web;

    public partial class news
    {
        public news()
        {
            this.contents = new HashSet<content>();
        }
    
        public int id { get; set; }
        public string title { get; set; }
        public Nullable<System.DateTime> date_news { get; set; }
        public string image { get; set; }
    
        public virtual ICollection<content> contents { get; set; }
        public int RowNumber { get; internal set; }
        [NotMapped]
        public HttpPostedFileBase ImageUpload { get; set; }
    }
}
