//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace hotel_bookings.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class rating_view
    {
        public int id { get; set; }
        public int booking_order_id { get; set; }
        public Nullable<int> room_id { get; set; }
        public Nullable<int> user_id { get; set; }
        public string review { get; set; }
        public Nullable<int> rating { get; set; }
        public Nullable<System.DateTime> review_day { get; set; }
        public Nullable<int> seen { get; set; }
    
        public virtual booking_order booking_order { get; set; }
        public virtual room room { get; set; }
        public virtual user user { get; set; }
    }
}
