//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace hotel_bookings.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Web;

    public partial class room
    {
        public room()
        {
            this.booking_details = new HashSet<booking_details>();
            this.rating_view = new HashSet<rating_view>();
            this.room_feature = new HashSet<room_feature>();
            this.room_images = new HashSet<room_images>();
        }
        public int RowNumber { get; set; }

        public int id { get; set; }
        public int room_style_id { get; set; }
        public string name { get; set; }
        public Nullable<int> adult { get; set; }
        public Nullable<int> children { get; set; }
        public Nullable<int> price { get; set; }
        public Nullable<int> area { get; set; }
        public string description { get; set; }
        public string avatar { get; set; }
        public Nullable<int> quantity { get; set; }
        public Nullable<int> status { get; set; }
        

        public virtual ICollection<booking_details> booking_details { get; set; }
        public virtual ICollection<rating_view> rating_view { get; set; }
        public virtual ICollection<room_feature> room_feature { get; set; }
        public virtual ICollection<room_images> room_images { get; set; }
        public virtual room_style room_style { get; set; }
        [NotMapped]
        public HttpPostedFileBase ImageUpload { get; set; }
    }
}
