//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace hotel_bookings.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class room_feature
    {
        public int features_id { get; set; }
        public int room_id { get; set; }
        public string note { get; set; }
    
        public virtual feature feature { get; set; }
        public virtual room room { get; set; }
    }
}
