//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace hotel_bookings.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sale
    {
        public sale()
        {
            this.room_sale = new HashSet<room_sale>();
        }
    
        public int id { get; set; }
        public Nullable<int> percents { get; set; }
    
        public virtual ICollection<room_sale> room_sale { get; set; }
    }
}
