//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace hotel_bookings.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class service
    {
        public service()
        {
            this.order_service = new HashSet<order_service>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public Nullable<int> price { get; set; }
        public string image { get; set; }
        public string description { get; set; }
    
        public virtual ICollection<order_service> order_service { get; set; }
    }
}
